using System.Collections.Generic;
using TMPro;
using UnityEngine;
using UnityEngine.Rendering.Universal;
using UnityEngine.SceneManagement;
using UnityEngine.UI;

// Dresses each chapter's room in pixel art at runtime, without touching the
// gameplay scripts or needing anything set up in the scene. Each chapter's
// room, furniture, task art and mood overlay is listed in ArtByChapter
// below; a chapter that isn't listed keeps its placeholder squares.
//
// It installs itself automatically whenever a scene with a GameManager
// loads (see Install below), then:
//   - hides the placeholder squares and draws the chapter's room
//   - adds invisible blockers for the furniture drawn into the room
//   - swaps each task's sprite by taskId, with "not done" and "done" states,
//     and cold versions that stay behind as traces in Self Hour
//   - draws her in Partner Hour and the partner in Self Hour, with 4-way
//     facing and a 2-frame walk
//   - marks the traces still left in Self Hour with a small sparkle
//   - adds the chapter's mood overlay (Chapter 1: green "nausea" vignette
//     that deepens as Body drops; Chapter 2: grey "worry" vignette and
//     thought bubbles as Mind drops), and an evening tint in Self Hour
//   - restyles the meters, panels, buttons and text (Pixelify Sans font)
//
// To turn it off, set AutoInstall to false.
//
// All sprites are 32x32 px per grid cell (32 pixels per unit) and live in
// Assets/Resources/PixelArt. They are generated by Tools/pixel_art/generate_sprites.py
// (Chapter 1) and generate_sprites_ch2.py (Chapter 2), so they can be
// regenerated or tweaked there.
public class PixelArtSkin : MonoBehaviour
{
    public static bool AutoInstall = true;

    const string Root = "PixelArt/";

    // Runs once when the game starts (for the first scene), and then on
    // every later scene load, so moving from Chapter 1 to Chapter 2 with
    // the Next Chapter button gets the new chapter's art too.
    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]
    static void Install()
    {
        SceneManager.sceneLoaded -= OnSceneLoaded;   // never subscribe twice
        SceneManager.sceneLoaded += OnSceneLoaded;
        TryInstall(SceneManager.GetActiveScene());
    }

    static void OnSceneLoaded(Scene scene, LoadSceneMode mode)
    {
        TryInstall(scene);
    }

    static void TryInstall(Scene scene)
    {
        if (!AutoInstall) return;

        var gm = FindFirstObjectByType<GameManager>();
        if (gm == null || gm.gameObject.scene != scene) return;

        // Each chapter's art is hand-built for that chapter's room and task
        // set. A chapter without an entry in ArtByChapter falls back to the
        // placeholder squares rather than having another chapter's room
        // painted over it.
        if (gm.chapterData == null || !ArtByChapter.ContainsKey(gm.chapterData.chapterNumber)) return;

        foreach (var existing in FindObjectsByType<PixelArtSkin>(FindObjectsSortMode.None))
        {
            if (existing.gameObject.scene == scene) return;   // already dressed
        }

        var go = new GameObject("PixelArtSkin");
        SceneManager.MoveGameObjectToScene(go, scene);
        go.AddComponent<PixelArtSkin>();
    }

    // ---------- Which art goes with which chapter ----------

    class TaskArt
    {
        public string[] todo;      // animated while waiting to be done (Partner Hour)
        public string done;        // after it's done
        public string[] trace;     // left undone, seen in Self Hour (can animate)
    }

    // The main (hold) task: a different look before, during and after the hold.
    class HoldArt
    {
        public string idle;           // before the hold starts
        public string[] active;       // while holding
        public float activeFps = 1.5f;
        public string completed;      // held to the end
        public string cancelled;      // let go early (or never started)
    }

    enum Mood { Nausea, Worry }

    class ChapterArt
    {
        public string room;                 // full-room sprite, 11 x 10 cells, x -5..5, y -4..5
        public string herPrefix = "her";    // her sprites: <prefix>_<down|up|side>_<0|1>
        public Mood mood;
        public Dictionary<string, TaskArt> tasks;
        public HoldArt hold;
        // Grid cells (x, y) covered by furniture drawn into the room. They get
        // invisible colliders on the Solid layer so the player can't walk
        // through the fridge or the cot.
        public Vector2Int[] furniture;
    }

    static readonly Dictionary<int, ChapterArt> ArtByChapter = new Dictionary<int, ChapterArt>
    {
        {
            1, new ChapterArt
            {
                room = "room_base",
                mood = Mood.Nausea,
                tasks = new Dictionary<string, TaskArt>
                {
                    { "dishes", new TaskArt { todo = new[] { "sink_dirty" }, done = "sink_clean", trace = new[] { "sink_dirty" } } },
                    { "stove",  new TaskArt { todo = new[] { "stove_cooking_0", "stove_cooking_1" }, done = "stove_off", trace = new[] { "stove_cold" } } },
                    { "coffee", new TaskArt { todo = new[] { "coffee_full_0", "coffee_full_1" }, done = "coffee_done", trace = new[] { "coffee_cold" } } },
                },
                hold = new HoldArt
                {
                    idle = "laptop_idle",
                    active = new[] { "laptop_call_0", "laptop_call_1", "laptop_call_2", "laptop_call_3" },
                    completed = "laptop_closed",
                    cancelled = "laptop_closed",
                },
                furniture = new[]
                {
                    new Vector2Int(-4, 3), new Vector2Int(-2, 3), new Vector2Int(-1, 3),   // fridge, counters
                    new Vector2Int(1, 3), new Vector2Int(2, 3), new Vector2Int(4, 3),      // counters, fruit bowl
                    new Vector2Int(-4, -2),                                                // desk beside the laptop
                    new Vector2Int(-4, -3), new Vector2Int(4, -3),                         // plants
                    new Vector2Int(2, -3), new Vector2Int(3, -3),                          // couch
                    new Vector2Int(2, -2), new Vector2Int(3, -2),                          // coffee table
                    new Vector2Int(4, 1),                                                  // laundry basket
                },
            }
        },
        {
            2, new ChapterArt
            {
                room = "room_base_ch2",
                herPrefix = "her_bump",
                mood = Mood.Worry,
                tasks = new Dictionary<string, TaskArt>
                {
                    { "dinner",   new TaskArt { todo = new[] { "stove_cooking_0", "stove_cooking_1" }, done = "stove_off", trace = new[] { "stove_cold" } } },
                    { "washing",  new TaskArt { todo = new[] { "washer_running_0", "washer_running_1" }, done = "washer_done", trace = new[] { "washer_wet_0", "washer_wet_1" } } },
                    { "mum_call", new TaskArt { todo = new[] { "phone_ring_0", "phone_ring_1" }, done = "phone_down", trace = new[] { "phone_missed" } } },
                    { "searches", new TaskArt { todo = new[] { "search_scroll_0", "search_scroll_1", "search_scroll_2" }, done = "search_down", trace = new[] { "search_left_open" } } },
                },
                hold = new HoldArt
                {
                    idle = "nursery_idle",
                    active = new[] { "nursery_sorting_0", "nursery_sorting_1", "nursery_sorting_2", "nursery_sorting_3" },
                    activeFps = 3f,
                    completed = "nursery_done",
                    cancelled = "nursery_half_unpacked",
                },
                furniture = new[]
                {
                    new Vector2Int(-4, 3), new Vector2Int(-3, 3), new Vector2Int(-2, 3), new Vector2Int(-1, 3),   // fridge, sink, counters
                    new Vector2Int(1, 3), new Vector2Int(2, 3), new Vector2Int(4, 3),                            // counters, fruit bowl
                    new Vector2Int(-4, -2),                                                                      // desk beside the phone
                    new Vector2Int(-4, -3),                                                                      // plant
                    new Vector2Int(4, -1),                                                                       // armchair
                    new Vector2Int(1, -3),                                                                       // car seat box
                    new Vector2Int(3, -3), new Vector2Int(4, -3),                                                // cot
                },
            }
        },
    };

    static readonly Color BodyColor = new Color32(216, 90, 48, 255);
    static readonly Color MindColor = new Color32(239, 159, 39, 255);
    static readonly Color PersonColor = new Color32(29, 158, 117, 255);
    static readonly Color MaskColor = new Color32(127, 119, 221, 255);
    static readonly Color TextDark = new Color32(43, 34, 51, 255);
    static readonly Color Background = new Color32(34, 28, 40, 255);

    enum Phase { Other, Partner, Self }

    GameManager gm;
    GridPlayerController player;
    SpriteRenderer playerRenderer;
    readonly Dictionary<string, Sprite> cache = new Dictionary<string, Sprite>();
    readonly HashSet<InteractableTask> doneInPartnerHour = new HashSet<InteractableTask>();
    readonly Dictionary<InteractableTask, SpriteRenderer> markers = new Dictionary<InteractableTask, SpriteRenderer>();

    ChapterArt art;
    InteractableTask holdTask;
    enum HoldState { Idle, Active, Completed, Cancelled }
    HoldState holdState = HoldState.Idle;
    SpriteRenderer worryBubble;

    Image moodVignette;
    Image eveningTint;
    Image eveningVignette;
    TMP_FontAsset pixelFont;
    float nextFontSweep;
    Phase phase = Phase.Other;

    // ---------- Setup ----------

    void Start()
    {
        gm = FindFirstObjectByType<GameManager>();
        if (gm == null || gm.chapterData == null || !ArtByChapter.TryGetValue(gm.chapterData.chapterNumber, out art))
        {
            Destroy(gameObject);
            return;
        }
        player = FindFirstObjectByType<GridPlayerController>();
        if (player != null) playerRenderer = player.GetComponent<SpriteRenderer>();

        SetUpCamera();
        BuildRoom();
        SetUpTasks();
        BuildOverlays();
        RestyleUi();
        LoadFont();
        SweepFonts();
    }

    Sprite S(string name)
    {
        if (cache.TryGetValue(name, out var s)) return s;
        s = Resources.Load<Sprite>(Root + name);
        if (s == null) Debug.LogWarning($"PixelArtSkin: missing sprite Resources/{Root}{name}");
        cache[name] = s;
        return s;
    }

    void SetUpCamera()
    {
        var cam = Camera.main;
        if (cam == null) return;

        cam.backgroundColor = Background;
        // The room's top wall is two rows tall, so centre the view half a
        // cell higher than the grid's centre.
        var p = cam.transform.position;
        cam.transform.position = new Vector3(0f, 0.5f, p.z);

        // Integer pixel scaling keeps the pixel art crisp: 640x360 at 32
        // pixels per unit is exactly 3x at 1080p and 2x at 720p.
        var ppc = cam.GetComponent<PixelPerfectCamera>();
        if (ppc == null) ppc = cam.gameObject.AddComponent<PixelPerfectCamera>();
        ppc.assetsPPU = 32;
        ppc.refResolutionX = 640;
        ppc.refResolutionY = 360;
    }

    void BuildRoom()
    {
        // Hide the placeholder coloured squares (walls, floor) but keep
        // their colliders, so movement works exactly as before.
        var room = GameObject.Find("Room");
        if (room != null)
        {
            foreach (var sr in room.GetComponentsInChildren<SpriteRenderer>(true))
            {
                if (sr.GetComponent<InteractableTask>() == null) sr.enabled = false;
            }
        }

        // The room sprite covers x -5..5 and y -4..5 (11 x 10 cells).
        var baseGo = new GameObject("PixelRoomBase");
        baseGo.transform.SetParent(transform, false);
        baseGo.transform.position = new Vector3(0f, 0.5f, 0f);
        var baseSr = baseGo.AddComponent<SpriteRenderer>();
        baseSr.sprite = S(art.room);
        baseSr.sortingOrder = -10;

        int solidLayer = FirstLayerIn(player != null ? player.solidLayer : (LayerMask)0);
        foreach (var c in art.furniture)
        {
            var go = new GameObject($"Blocker_{c.x}_{c.y}");
            go.transform.SetParent(transform, false);
            go.transform.position = new Vector3(c.x, c.y, 0f);
            if (solidLayer >= 0) go.layer = solidLayer;
            go.AddComponent<BoxCollider2D>().size = Vector2.one * 0.95f;
        }
    }

    static int FirstLayerIn(LayerMask mask)
    {
        for (int i = 0; i < 32; i++)
        {
            if ((mask.value & (1 << i)) != 0) return i;
        }
        return LayerMask.NameToLayer("Solid");
    }

    void SetUpTasks()
    {
        foreach (var task in InteractableTask.All)
        {
            var sr = task.GetComponent<SpriteRenderer>();
            if (sr != null)
            {
                sr.color = Color.white;
                sr.sortingOrder = 0;
            }

            if (task.RequiresHold && task.taskId == gm.chapterData.choiceTriggerTaskId)
            {
                holdTask = task;
                holdTask.HoldStarted += _ => holdState = HoldState.Active;
                holdTask.HoldCompleted += _ => holdState = HoldState.Completed;
                holdTask.HoldCancelled += _ => holdState = HoldState.Cancelled;
            }
        }
    }

    // ---------- Overlays (mood, evening) ----------

    void BuildOverlays()
    {
        var canvasGo = new GameObject("PixelArtOverlays");
        canvasGo.transform.SetParent(transform, false);
        var canvas = canvasGo.AddComponent<Canvas>();
        canvas.renderMode = RenderMode.ScreenSpaceOverlay;
        canvas.sortingOrder = -100; // under the game's own UI, over the room

        eveningTint = MakeFullScreen(canvasGo.transform, "EveningTint", null, new Color(1f, 0.55f, 0.35f, 0f));
        eveningVignette = MakeFullScreen(canvasGo.transform, "EveningVignette", S("vignette"), new Color(0.13f, 0.1f, 0.2f, 0f));
        Color moodColor = art.mood == Mood.Nausea
            ? new Color(0.55f, 0.7f, 0.38f, 0f)    // queasy green
            : new Color(0.43f, 0.41f, 0.59f, 0f);  // grey-violet worry
        moodVignette = MakeFullScreen(canvasGo.transform, "MoodVignette", S("vignette"), moodColor);

        if (art.mood == Mood.Worry)
        {
            var go = new GameObject("WorryBubble");
            go.transform.SetParent(transform, false);
            worryBubble = go.AddComponent<SpriteRenderer>();
            worryBubble.sprite = S("worry_bubble");
            worryBubble.sortingOrder = 21;
            worryBubble.enabled = false;
        }
    }

    static Image MakeFullScreen(Transform parent, string name, Sprite sprite, Color color)
    {
        var go = new GameObject(name);
        go.transform.SetParent(parent, false);
        var rt = go.AddComponent<RectTransform>();
        rt.anchorMin = Vector2.zero;
        rt.anchorMax = Vector2.one;
        rt.offsetMin = Vector2.zero;
        rt.offsetMax = Vector2.zero;
        var img = go.AddComponent<Image>();
        img.sprite = sprite;
        img.color = color;
        img.raycastTarget = false;
        return img;
    }

    // ---------- UI restyle ----------

    void RestyleUi()
    {
        if (gm == null) return;

        // The hour panels used full-screen photos, which covered the room.
        // Keep the panels (they hold the HUD), drop their backgrounds.
        HideImage(gm.partnerHourPanel);
        HideImage(gm.selfHourPanel);

        if (gm.meters != null)
        {
            StyleMeter(gm.meters.body, BodyColor);
            StyleMeter(gm.meters.mind, MindColor);
            StyleMeter(gm.meters.feelingLikeAPerson, PersonColor);
            StyleMeter(gm.meters.mask, MaskColor);
        }

        if (gm.checklist != null) StylePanel(gm.checklist.container);
        if (gm.juggle != null) StylePanel(gm.juggle.container);

        foreach (var button in FindObjectsByType<Button>(FindObjectsInactive.Include, FindObjectsSortMode.None))
        {
            var img = button.GetComponent<Image>();
            if (img != null)
            {
                img.sprite = S("ui_button");
                img.type = Image.Type.Sliced;
                img.color = Color.white;
            }
            foreach (var t in button.GetComponentsInChildren<TMP_Text>(true)) t.color = TextDark;
        }
    }

    static void HideImage(GameObject panel)
    {
        if (panel == null) return;
        var img = panel.GetComponent<Image>();
        if (img != null) img.enabled = false;
    }

    void StylePanel(RectTransform rt)
    {
        if (rt == null) return;
        var img = rt.GetComponent<Image>();
        if (img == null) img = rt.gameObject.AddComponent<Image>();
        img.sprite = S("ui_panel");
        img.type = Image.Type.Sliced;
        img.color = Color.white;
    }

    void StyleMeter(Slider slider, Color color)
    {
        if (slider == null) return;
        if (slider.fillRect != null)
        {
            var fill = slider.fillRect.GetComponent<Image>();
            if (fill != null)
            {
                fill.sprite = S("ui_meter_fill");
                fill.type = Image.Type.Sliced;
                fill.pixelsPerUnitMultiplier = 2f; // thinner frame so it fits a slim bar
                fill.color = color;
            }
        }
        var bg = slider.transform.Find("Background");
        if (bg != null)
        {
            var img = bg.GetComponent<Image>();
            if (img != null)
            {
                img.sprite = S("ui_meter_bg");
                img.type = Image.Type.Sliced;
                img.pixelsPerUnitMultiplier = 2f;
                img.color = Color.white;
            }
        }
    }

    void LoadFont()
    {
        var font = Resources.Load<Font>(Root + "Fonts/PixelifySans-Regular");
        if (font == null) return;

        pixelFont = TMP_FontAsset.CreateFontAsset(font);
        if (pixelFont == null) return;
        pixelFont.name = "PixelifySans (runtime)";

        // Fall back to the project's default font for symbols Pixelify
        // doesn't have (the checklist's tick boxes, for example).
        var fallback = TMP_Settings.defaultFontAsset;
        if (fallback != null)
        {
            if (pixelFont.fallbackFontAssetTable == null) pixelFont.fallbackFontAssetTable = new List<TMP_FontAsset>();
            pixelFont.fallbackFontAssetTable.Add(fallback);
        }
    }

    // Checklist rows, juggle prompts and the world prompt are created at
    // runtime with the default font, so re-apply the pixel font now and then.
    void SweepFonts()
    {
        if (pixelFont == null) return;
        foreach (var t in FindObjectsByType<TMP_Text>(FindObjectsInactive.Include, FindObjectsSortMode.None))
        {
            if (t.font != pixelFont) t.font = pixelFont;
        }
    }

    // ---------- Per-frame state ----------

    void Update()
    {
        if (art == null) return;   // this chapter has no art; being destroyed

        UpdatePhase();
        UpdateTasks();
        UpdatePlayer();
        UpdateMarkers();
        UpdateOverlays();

        if (Time.unscaledTime >= nextFontSweep)
        {
            nextFontSweep = Time.unscaledTime + 0.5f;
            SweepFonts();
        }
    }

    void UpdatePhase()
    {
        Phase now = Phase.Other;
        if (gm != null)
        {
            if (gm.partnerHourPanel != null && gm.partnerHourPanel.activeInHierarchy) now = Phase.Partner;
            else if (gm.selfHourPanel != null && gm.selfHourPanel.activeInHierarchy) now = Phase.Self;
        }

        if (now == phase) return;

        if (now == Phase.Partner)
        {
            doneInPartnerHour.Clear();
            holdState = HoldState.Idle;
        }
        phase = now;
    }

    void UpdateTasks()
    {
        int frame2 = Mathf.FloorToInt(Time.time * 2.5f);

        foreach (var task in InteractableTask.All)
        {
            var sr = task.GetComponent<SpriteRenderer>();
            if (sr == null) continue;

            if (task == holdTask)
            {
                sr.sprite = HoldSprite();
                continue;
            }

            if (!art.tasks.TryGetValue(task.taskId, out var taskArt)) continue;

            // During Partner Hour a task that gets locked has just been done.
            if (phase == Phase.Partner && task.locked) doneInPartnerHour.Add(task);

            string name;
            if (phase == Phase.Self)
            {
                name = doneInPartnerHour.Contains(task) ? taskArt.done : taskArt.trace[frame2 % taskArt.trace.Length];
            }
            else if (doneInPartnerHour.Contains(task))
            {
                name = taskArt.done;
            }
            else
            {
                name = taskArt.todo[frame2 % taskArt.todo.Length];
            }
            sr.sprite = S(name);
        }
    }

    Sprite HoldSprite()
    {
        var h = art.hold;
        switch (holdState)
        {
            case HoldState.Active: return S(h.active[Mathf.FloorToInt(Time.time * h.activeFps) % h.active.Length]);
            case HoldState.Completed: return S(h.completed);
            case HoldState.Cancelled: return S(h.cancelled);
            default:
                // Never started: in Self Hour that reads the same as letting go early.
                return S(phase == Phase.Self ? h.cancelled : h.idle);
        }
    }

    void UpdatePlayer()
    {
        if (player == null || playerRenderer == null) return;

        string who = phase == Phase.Self ? "partner" : art.herPrefix;
        string facing;
        bool flip = false;
        switch (player.Facing)
        {
            case GridPlayerController.Direction.Up: facing = "up"; break;
            case GridPlayerController.Direction.Left: facing = "side"; flip = true; break;
            case GridPlayerController.Direction.Right: facing = "side"; break;
            default: facing = "down"; break;
        }

        int frame = player.IsMoving ? (Mathf.FloorToInt(Time.time * 10f) % 2) : 0;
        playerRenderer.sprite = S($"{who}_{facing}_{frame}");
        playerRenderer.flipX = flip;
        playerRenderer.color = Color.white;
        playerRenderer.sortingOrder = 5;
    }

    void UpdateMarkers()
    {
        float bob = Mathf.Round(Mathf.Sin(Time.time * 4f) * 2f) / 32f; // whole pixels
        foreach (var task in InteractableTask.All)
        {
            bool show = phase == Phase.Self && !task.RequiresHold && !task.locked;

            if (!markers.TryGetValue(task, out var marker))
            {
                if (!show) continue;
                var go = new GameObject($"TraceMarker_{task.taskId}");
                go.transform.SetParent(transform, false);
                marker = go.AddComponent<SpriteRenderer>();
                marker.sprite = S("trace_marker");
                marker.sortingOrder = 20;
                markers[task] = marker;
            }

            marker.enabled = show;
            if (show) marker.transform.position = task.transform.position + new Vector3(0f, 0.75f + bob, 0f);
        }
    }

    void UpdateOverlays()
    {
        if (moodVignette == null) return;

        // Chapter 1 is driven by Body (nausea), Chapter 2 by Mind (worry).
        Slider driver = null;
        if (gm.meters != null) driver = art.mood == Mood.Nausea ? gm.meters.body : gm.meters.mind;
        float value = driver != null ? driver.value : 1f;
        float target = phase == Phase.Partner ? Mathf.Clamp01((1f - value) * 1.1f) * 0.85f : 0f;
        // A slow, uneasy pulse that grows as the meter drops.
        float pulse = 1f + Mathf.Sin(Time.time * 1.7f) * 0.15f * target;
        SetAlpha(moodVignette, Mathf.MoveTowards(moodVignette.color.a, target * pulse, Time.deltaTime));

        UpdateWorryBubble(value);

        bool evening = phase == Phase.Self;
        SetAlpha(eveningTint, Mathf.MoveTowards(eveningTint.color.a, evening ? 0.12f : 0f, Time.deltaTime * 0.5f));
        SetAlpha(eveningVignette, Mathf.MoveTowards(eveningVignette.color.a, evening ? 0.55f : 0f, Time.deltaTime * 0.5f));
    }

    // Thought bubbles pop up over her more often as Mind drops: one every
    // few seconds at first, almost constantly near the bottom.
    float nextBubbleTime;
    float bubbleHideTime;

    void UpdateWorryBubble(float mind)
    {
        if (worryBubble == null) return;

        bool canShow = phase == Phase.Partner && player != null && mind < 0.8f;
        if (!canShow)
        {
            worryBubble.enabled = false;
            return;
        }

        if (!worryBubble.enabled && Time.time >= nextBubbleTime)
        {
            worryBubble.enabled = true;
            bubbleHideTime = Time.time + 1.4f;
        }
        else if (worryBubble.enabled && Time.time >= bubbleHideTime)
        {
            worryBubble.enabled = false;
            nextBubbleTime = Time.time + Mathf.Lerp(0.4f, 5f, mind / 0.8f);
        }

        if (worryBubble.enabled)
        {
            float bob = Mathf.Round(Mathf.Sin(Time.time * 3f) * 1.5f) / 32f;
            worryBubble.transform.position = player.transform.position + new Vector3(0.5f, 0.85f + bob, 0f);
        }
    }

    static void SetAlpha(Image img, float a)
    {
        var c = img.color;
        c.a = a;
        img.color = c;
    }
}
