using System.Collections.Generic;
using TMPro;
using UnityEngine;
using UnityEngine.Rendering.Universal;
using UnityEngine.UI;

// Dresses the Chapter 1 room in pixel art at runtime, without touching the
// gameplay scripts or needing anything set up in the scene.
//
// It installs itself automatically whenever a scene with a GameManager
// loads (see Install below), then:
//   - hides the placeholder squares and draws the room (Resources/PixelArt/room_base)
//   - adds invisible blockers for the furniture drawn into the room
//   - swaps each task's sprite by taskId, with "not done" and "done" states,
//     and cold versions that stay behind as traces in Self Hour
//   - draws her in Partner Hour and the partner in Self Hour, with 4-way
//     facing and a 2-frame walk
//   - marks the traces still left in Self Hour with a small sparkle
//   - adds a green "nausea" vignette that deepens as Body drops, and an
//     evening tint in Self Hour
//   - restyles the meters, panels, buttons and text (Pixelify Sans font)
//
// To turn it off, set AutoInstall to false.
//
// All sprites are 32x32 px per grid cell (32 pixels per unit) and live in
// Assets/Resources/PixelArt. They are generated by Tools/pixel_art/generate_sprites.py,
// so they can be regenerated or tweaked there.
public class PixelArtSkin : MonoBehaviour
{
    public static bool AutoInstall = true;

    const string Root = "PixelArt/";

    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]
    static void Install()
    {
        if (!AutoInstall) return;
        if (FindFirstObjectByType<GameManager>() == null) return;
        if (FindFirstObjectByType<PixelArtSkin>() != null) return;
        new GameObject("PixelArtSkin").AddComponent<PixelArtSkin>();
    }

    // ---------- Which art goes with which taskId ----------

    class TaskArt
    {
        public string[] todo;      // animated while waiting to be done (Partner Hour)
        public string done;        // after it's done
        public string trace;       // left undone, seen in Self Hour
    }

    static readonly Dictionary<string, TaskArt> TaskArtById = new Dictionary<string, TaskArt>
    {
        { "dishes", new TaskArt { todo = new[] { "sink_dirty" }, done = "sink_clean", trace = "sink_dirty" } },
        { "stove",  new TaskArt { todo = new[] { "stove_cooking_0", "stove_cooking_1" }, done = "stove_off", trace = "stove_cold" } },
        { "coffee", new TaskArt { todo = new[] { "coffee_full_0", "coffee_full_1" }, done = "coffee_done", trace = "coffee_cold" } },
    };

    // Grid cells (x, y) covered by furniture that's drawn into room_base.
    // They get invisible colliders on the Solid layer so the player can't
    // walk through the fridge or the couch.
    static readonly Vector2Int[] FurnitureCells =
    {
        new Vector2Int(-4, 3), new Vector2Int(-2, 3), new Vector2Int(-1, 3),   // fridge, counters
        new Vector2Int(1, 3), new Vector2Int(2, 3), new Vector2Int(4, 3),      // counters, fruit bowl
        new Vector2Int(-4, -2),                                                // desk beside the laptop
        new Vector2Int(-4, -3), new Vector2Int(4, -3),                         // plants
        new Vector2Int(2, -3), new Vector2Int(3, -3),                          // couch
        new Vector2Int(2, -2), new Vector2Int(3, -2),                          // coffee table
        new Vector2Int(4, 1),                                                  // laundry basket
    };

    static readonly Color BodyColor = new Color32(216, 90, 48, 255);
    static readonly Color MindColor = new Color32(239, 159, 39, 255);
    static readonly Color PersonColor = new Color32(29, 158, 117, 255);
    static readonly Color MaskColor = new Color32(127, 119, 221, 255);
    static readonly Color TextDark = new Color32(43, 34, 51, 255);
    static readonly Color Background = new Color32(34, 28, 40, 255);

    enum Phase { Other, Partner, Self }

    GameManager gm;
    GridPlayerController player;
    SpriteRenderer playerRenderer;
    readonly Dictionary<string, Sprite> cache = new Dictionary<string, Sprite>();
    readonly HashSet<InteractableTask> doneInPartnerHour = new HashSet<InteractableTask>();
    readonly Dictionary<InteractableTask, SpriteRenderer> markers = new Dictionary<InteractableTask, SpriteRenderer>();

    InteractableTask laptop;
    enum LaptopState { Idle, Call, Closed }
    LaptopState laptopState = LaptopState.Idle;

    Image nauseaVignette;
    Image eveningTint;
    Image eveningVignette;
    TMP_FontAsset pixelFont;
    float nextFontSweep;
    Phase phase = Phase.Other;

    // ---------- Setup ----------

    void Start()
    {
        gm = FindFirstObjectByType<GameManager>();
        player = FindFirstObjectByType<GridPlayerController>();
        if (player != null) playerRenderer = player.GetComponent<SpriteRenderer>();

        SetUpCamera();
        BuildRoom();
        SetUpTasks();
        BuildOverlays();
        RestyleUi();
        LoadFont();
        SweepFonts();
    }

    Sprite S(string name)
    {
        if (cache.TryGetValue(name, out var s)) return s;
        s = Resources.Load<Sprite>(Root + name);
        if (s == null) Debug.LogWarning($"PixelArtSkin: missing sprite Resources/{Root}{name}");
        cache[name] = s;
        return s;
    }

    void SetUpCamera()
    {
        var cam = Camera.main;
        if (cam == null) return;

        cam.backgroundColor = Background;
        // The room's top wall is two rows tall, so centre the view half a
        // cell higher than the grid's centre.
        var p = cam.transform.position;
        cam.transform.position = new Vector3(0f, 0.5f, p.z);

        // Integer pixel scaling keeps the pixel art crisp: 640x360 at 32
        // pixels per unit is exactly 3x at 1080p and 2x at 720p.
        var ppc = cam.GetComponent<PixelPerfectCamera>();
        if (ppc == null) ppc = cam.gameObject.AddComponent<PixelPerfectCamera>();
        ppc.assetsPPU = 32;
        ppc.refResolutionX = 640;
        ppc.refResolutionY = 360;
    }

    void BuildRoom()
    {
        // Hide the placeholder coloured squares (walls, floor) but keep
        // their colliders, so movement works exactly as before.
        var room = GameObject.Find("Room");
        if (room != null)
        {
            foreach (var sr in room.GetComponentsInChildren<SpriteRenderer>(true))
            {
                if (sr.GetComponent<InteractableTask>() == null) sr.enabled = false;
            }
        }

        // room_base covers x -5..5 and y -4..5 (11 x 10 cells).
        var baseGo = new GameObject("PixelRoomBase");
        baseGo.transform.SetParent(transform, false);
        baseGo.transform.position = new Vector3(0f, 0.5f, 0f);
        var baseSr = baseGo.AddComponent<SpriteRenderer>();
        baseSr.sprite = S("room_base");
        baseSr.sortingOrder = -10;

        int solidLayer = FirstLayerIn(player != null ? player.solidLayer : (LayerMask)0);
        foreach (var c in FurnitureCells)
        {
            var go = new GameObject($"Blocker_{c.x}_{c.y}");
            go.transform.SetParent(transform, false);
            go.transform.position = new Vector3(c.x, c.y, 0f);
            if (solidLayer >= 0) go.layer = solidLayer;
            go.AddComponent<BoxCollider2D>().size = Vector2.one * 0.95f;
        }
    }

    static int FirstLayerIn(LayerMask mask)
    {
        for (int i = 0; i < 32; i++)
        {
            if ((mask.value & (1 << i)) != 0) return i;
        }
        return LayerMask.NameToLayer("Solid");
    }

    void SetUpTasks()
    {
        foreach (var task in InteractableTask.All)
        {
            var sr = task.GetComponent<SpriteRenderer>();
            if (sr != null)
            {
                sr.color = Color.white;
                sr.sortingOrder = 0;
            }

            if (task.RequiresHold && task.taskId == "laptop")
            {
                laptop = task;
                laptop.HoldStarted += _ => laptopState = LaptopState.Call;
                laptop.HoldCompleted += _ => laptopState = LaptopState.Closed;
                laptop.HoldCancelled += _ => laptopState = LaptopState.Closed;
            }
        }
    }

    // ---------- Overlays (nausea, evening) ----------

    void BuildOverlays()
    {
        var canvasGo = new GameObject("PixelArtOverlays");
        canvasGo.transform.SetParent(transform, false);
        var canvas = canvasGo.AddComponent<Canvas>();
        canvas.renderMode = RenderMode.ScreenSpaceOverlay;
        canvas.sortingOrder = -100; // under the game's own UI, over the room

        eveningTint = MakeFullScreen(canvasGo.transform, "EveningTint", null, new Color(1f, 0.55f, 0.35f, 0f));
        eveningVignette = MakeFullScreen(canvasGo.transform, "EveningVignette", S("vignette"), new Color(0.13f, 0.1f, 0.2f, 0f));
        nauseaVignette = MakeFullScreen(canvasGo.transform, "NauseaVignette", S("vignette"), new Color(0.55f, 0.7f, 0.38f, 0f));
    }

    static Image MakeFullScreen(Transform parent, string name, Sprite sprite, Color color)
    {
        var go = new GameObject(name);
        go.transform.SetParent(parent, false);
        var rt = go.AddComponent<RectTransform>();
        rt.anchorMin = Vector2.zero;
        rt.anchorMax = Vector2.one;
        rt.offsetMin = Vector2.zero;
        rt.offsetMax = Vector2.zero;
        var img = go.AddComponent<Image>();
        img.sprite = sprite;
        img.color = color;
        img.raycastTarget = false;
        return img;
    }

    // ---------- UI restyle ----------

    void RestyleUi()
    {
        if (gm == null) return;

        // The hour panels used full-screen photos, which covered the room.
        // Keep the panels (they hold the HUD), drop their backgrounds.
        HideImage(gm.partnerHourPanel);
        HideImage(gm.selfHourPanel);

        if (gm.meters != null)
        {
            StyleMeter(gm.meters.body, BodyColor);
            StyleMeter(gm.meters.mind, MindColor);
            StyleMeter(gm.meters.feelingLikeAPerson, PersonColor);
            StyleMeter(gm.meters.mask, MaskColor);
        }

        if (gm.checklist != null) StylePanel(gm.checklist.container);
        if (gm.juggle != null) StylePanel(gm.juggle.container);

        foreach (var button in FindObjectsByType<Button>(FindObjectsInactive.Include, FindObjectsSortMode.None))
        {
            var img = button.GetComponent<Image>();
            if (img != null)
            {
                img.sprite = S("ui_button");
                img.type = Image.Type.Sliced;
                img.color = Color.white;
            }
            foreach (var t in button.GetComponentsInChildren<TMP_Text>(true)) t.color = TextDark;
        }
    }

    static void HideImage(GameObject panel)
    {
        if (panel == null) return;
        var img = panel.GetComponent<Image>();
        if (img != null) img.enabled = false;
    }

    void StylePanel(RectTransform rt)
    {
        if (rt == null) return;
        var img = rt.GetComponent<Image>();
        if (img == null) img = rt.gameObject.AddComponent<Image>();
        img.sprite = S("ui_panel");
        img.type = Image.Type.Sliced;
        img.color = Color.white;
    }

    void StyleMeter(Slider slider, Color color)
    {
        if (slider == null) return;
        if (slider.fillRect != null)
        {
            var fill = slider.fillRect.GetComponent<Image>();
            if (fill != null)
            {
                fill.sprite = S("ui_meter_fill");
                fill.type = Image.Type.Sliced;
                fill.pixelsPerUnitMultiplier = 2f; // thinner frame so it fits a slim bar
                fill.color = color;
            }
        }
        var bg = slider.transform.Find("Background");
        if (bg != null)
        {
            var img = bg.GetComponent<Image>();
            if (img != null)
            {
                img.sprite = S("ui_meter_bg");
                img.type = Image.Type.Sliced;
                img.pixelsPerUnitMultiplier = 2f;
                img.color = Color.white;
            }
        }
    }

    void LoadFont()
    {
        var font = Resources.Load<Font>(Root + "Fonts/PixelifySans-Regular");
        if (font == null) return;

        pixelFont = TMP_FontAsset.CreateFontAsset(font);
        if (pixelFont == null) return;
        pixelFont.name = "PixelifySans (runtime)";

        // Fall back to the project's default font for symbols Pixelify
        // doesn't have (the checklist's tick boxes, for example).
        var fallback = TMP_Settings.defaultFontAsset;
        if (fallback != null)
        {
            if (pixelFont.fallbackFontAssetTable == null) pixelFont.fallbackFontAssetTable = new List<TMP_FontAsset>();
            pixelFont.fallbackFontAssetTable.Add(fallback);
        }
    }

    // Checklist rows, juggle prompts and the world prompt are created at
    // runtime with the default font, so re-apply the pixel font now and then.
    void SweepFonts()
    {
        if (pixelFont == null) return;
        foreach (var t in FindObjectsByType<TMP_Text>(FindObjectsInactive.Include, FindObjectsSortMode.None))
        {
            if (t.font != pixelFont) t.font = pixelFont;
        }
    }

    // ---------- Per-frame state ----------

    void Update()
    {
        UpdatePhase();
        UpdateTasks();
        UpdatePlayer();
        UpdateMarkers();
        UpdateOverlays();

        if (Time.unscaledTime >= nextFontSweep)
        {
            nextFontSweep = Time.unscaledTime + 0.5f;
            SweepFonts();
        }
    }

    void UpdatePhase()
    {
        Phase now = Phase.Other;
        if (gm != null)
        {
            if (gm.partnerHourPanel != null && gm.partnerHourPanel.activeInHierarchy) now = Phase.Partner;
            else if (gm.selfHourPanel != null && gm.selfHourPanel.activeInHierarchy) now = Phase.Self;
        }

        if (now == phase) return;

        if (now == Phase.Partner)
        {
            doneInPartnerHour.Clear();
            laptopState = LaptopState.Idle;
        }
        phase = now;
    }

    void UpdateTasks()
    {
        int frame2 = Mathf.FloorToInt(Time.time * 2.5f);

        foreach (var task in InteractableTask.All)
        {
            var sr = task.GetComponent<SpriteRenderer>();
            if (sr == null) continue;

            if (task == laptop)
            {
                sr.sprite = LaptopSprite();
                continue;
            }

            if (!TaskArtById.TryGetValue(task.taskId, out var art)) continue;

            // During Partner Hour a task that gets locked has just been done.
            if (phase == Phase.Partner && task.locked) doneInPartnerHour.Add(task);

            string name;
            if (phase == Phase.Self)
            {
                name = doneInPartnerHour.Contains(task) ? art.done : art.trace;
            }
            else if (doneInPartnerHour.Contains(task))
            {
                name = art.done;
            }
            else
            {
                name = art.todo[frame2 % art.todo.Length];
            }
            sr.sprite = S(name);
        }
    }

    Sprite LaptopSprite()
    {
        if (phase == Phase.Self) return S("laptop_closed");
        switch (laptopState)
        {
            case LaptopState.Call: return S("laptop_call_" + (Mathf.FloorToInt(Time.time * 1.5f) % 4));
            case LaptopState.Closed: return S("laptop_closed");
            default: return S("laptop_idle");
        }
    }

    void UpdatePlayer()
    {
        if (player == null || playerRenderer == null) return;

        string who = phase == Phase.Self ? "partner" : "her";
        string facing;
        bool flip = false;
        switch (player.Facing)
        {
            case GridPlayerController.Direction.Up: facing = "up"; break;
            case GridPlayerController.Direction.Left: facing = "side"; flip = true; break;
            case GridPlayerController.Direction.Right: facing = "side"; break;
            default: facing = "down"; break;
        }

        int frame = player.IsMoving ? (Mathf.FloorToInt(Time.time * 10f) % 2) : 0;
        playerRenderer.sprite = S($"{who}_{facing}_{frame}");
        playerRenderer.flipX = flip;
        playerRenderer.color = Color.white;
        playerRenderer.sortingOrder = 5;
    }

    void UpdateMarkers()
    {
        float bob = Mathf.Round(Mathf.Sin(Time.time * 4f) * 2f) / 32f; // whole pixels
        foreach (var task in InteractableTask.All)
        {
            bool show = phase == Phase.Self && !task.RequiresHold && !task.locked;

            if (!markers.TryGetValue(task, out var marker))
            {
                if (!show) continue;
                var go = new GameObject($"TraceMarker_{task.taskId}");
                go.transform.SetParent(transform, false);
                marker = go.AddComponent<SpriteRenderer>();
                marker.sprite = S("trace_marker");
                marker.sortingOrder = 20;
                markers[task] = marker;
            }

            marker.enabled = show;
            if (show) marker.transform.position = task.transform.position + new Vector3(0f, 0.75f + bob, 0f);
        }
    }

    void UpdateOverlays()
    {
        if (nauseaVignette == null) return;

        float body = (gm != null && gm.meters != null && gm.meters.body != null) ? gm.meters.body.value : 1f;
        float target = phase == Phase.Partner ? Mathf.Clamp01((1f - body) * 1.1f) * 0.85f : 0f;
        // A slow, uneasy pulse that grows with the nausea.
        float pulse = 1f + Mathf.Sin(Time.time * 1.7f) * 0.15f * target;
        SetAlpha(nauseaVignette, Mathf.MoveTowards(nauseaVignette.color.a, target * pulse, Time.deltaTime));

        bool evening = phase == Phase.Self;
        SetAlpha(eveningTint, Mathf.MoveTowards(eveningTint.color.a, evening ? 0.12f : 0f, Time.deltaTime * 0.5f));
        SetAlpha(eveningVignette, Mathf.MoveTowards(eveningVignette.color.a, evening ? 0.55f : 0f, Time.deltaTime * 0.5f));
    }

    static void SetAlpha(Image img, float a)
    {
        var c = img.color;
        c.a = a;
        img.color = c;
    }
}
